### ISSUE TITLE
DataManagement - Missing relationships field in VersionData model

### ISSUE THREAD

**Issue by yiskang** [autodesk-platform-services/aps-sdk-net#32] opened 2024-04-19 10:44 UTC
Hi Team,

There is one field called `relationships` in the version tip, but it's missing in the VersionData model. It's essential for SDK users to find storage id and derivative id/urn in this field.

<img width="990" alt="image" src="https://github.com/autodesk-platform-services/aps-sdk-net/assets/5725083/1144ef9f-7d2b-433b-9c57-7288566305a2">

<img width="1336" alt="image" src="https://github.com/autodesk-platform-services/aps-sdk-net/assets/5725083/56574580-5eeb-42f0-af5b-6bb25ed0533d">

**Comment by austincrft** [comment] 2024-04-23 17:52
this looks like a duplicate of the issue I filed: #30

**Comment by sajith-subramanian** [comment] 2024-10-21 10:37
This has been fixed as part of this release: https://www.nuget.org/packages/Autodesk.DataManagement/2.0.0-beta3
Please review it and let us know in case of any issues. Thanks!

**Closed by sajith-subramanian** 2024-10-21 10:37 UTC
